"""Contacts miration

Revision ID: 2583f5e3b622
Revises: 898df9e8ad71
Create Date: 2022-09-25 16:50:56.450008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2583f5e3b622'
down_revision = '898df9e8ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('phones',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.add_column('users', sa.Column('token_cookie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_cookie')
    op.drop_table('phones')
    op.drop_table('contacts')
    # ### end Alembic commands ###
