# Generated by Django 4.1.2 on 2022-10-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_financeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_id',
            new_name='category',
        ),
    ]
